### Exercise_Week08_Python
* import necessary libraries in the box below

In [80]:
import pandas as pd
import numpy as np

### Question 01
Create a NumPy array from [-60,-59,...,-1,0,1,2,3,...,60].

* Replace all odd numbers with -1

In [81]:
array_01 = np.arange(-60, 61)
array_01 = np.where(array_01 % 2 == 1, -1, array_01)
print(array_01)

[-60  -1 -58  -1 -56  -1 -54  -1 -52  -1 -50  -1 -48  -1 -46  -1 -44  -1
 -42  -1 -40  -1 -38  -1 -36  -1 -34  -1 -32  -1 -30  -1 -28  -1 -26  -1
 -24  -1 -22  -1 -20  -1 -18  -1 -16  -1 -14  -1 -12  -1 -10  -1  -8  -1
  -6  -1  -4  -1  -2  -1   0  -1   2  -1   4  -1   6  -1   8  -1  10  -1
  12  -1  14  -1  16  -1  18  -1  20  -1  22  -1  24  -1  26  -1  28  -1
  30  -1  32  -1  34  -1  36  -1  38  -1  40  -1  42  -1  44  -1  46  -1
  48  -1  50  -1  52  -1  54  -1  56  -1  58  -1  60]


### Question 02
With np.where, find the positions of:

* Find Elements in x where its value is more than its corresponding element in y.
* Elements in x where its value is equals to its corresponding element in y.

In [82]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 74, 29, 55, 4, 37, 18])
print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 5, 6, 7, 8, 9], dtype=int64),)
(array([0, 4], dtype=int64),)


### Question 03

Create a random 7×24 matrix representing hourly temperatures for one week.

(7 days, 24 Hour)

* Find the hour with the highest average temperature.
* Find the day with the highest average temperature.
* Compute the difference between max and min temperature.

In [83]:
array_03 = np.random.randint(-10, 50, size=(7, 24))
print(np.max(array_03))
print(np.max(np.round(np.mean(array_03, axis=1), 2)))
print(np.max(array_03) - np.min(array_03))

49
23.33
59


### Question 04
Create a 30×5 matrix (30 students, 5 courses).

* Compute each student's average.
* Compute each course average.
* Identify students who scored above 15 in at least 3 courses.
* Find the hardest course (with the loest scores)

In [84]:
array_04 = np.random.randint(0, 20, size=(30, 5))
print(np.round(np.mean(array_04, axis=1), 1))
print(np.round(np.mean(array_04, axis=0), 2))
more_than_15 = np.where(array_04 >= 15, 1, 0)
print(np.where(np.sum(more_than_15, axis=1) > 2))
print(np.where(np.mean(array_04, axis=0) == np.min(np.mean(array_04, axis=0))))

[ 8.2 13.  11.6 10.2  8.2 12.6 11.  11.6  6.4 13.   5.8  6.8  7.6  5.8
  7.8  9.   8.2  9.4  6.4  3.8 12.6  8.6 12.2  6.6 10.6 12.2  6.2  9.4
 13.4  7. ]
[ 7.97 10.87 10.07  9.3   7.67]
(array([25], dtype=int64),)
(array([4], dtype=int64),)


### Question 05

Generate two 1D arrays for 12 months:

Income array (values between 5000–15000)

Expenses array (values between 3000–12000)

* Compute monthly profit.
* Find the most profitable month.
* Identify loss months (profit < 0).

In [85]:
incom_array = np.random.randint(5000, 15001, size=12)
expense_array = np.random.randint(3000, 12001, size=12)
print(incom_array)
print(expense_array)
profit_array = incom_array - expense_array
print(profit_array)
print(np.where(profit_array == max(profit_array)))
print(np.where(profit_array < 0))

[12542 14949  6164 10463  7281 12743  8516  8050 13378 11286 13950 13437]
[ 5749  4598 11647  4967  3927  3131 10058  3197 11006  4279  3538  7217]
[ 6793 10351 -5483  5496  3354  9612 -1542  4853  2372  7007 10412  6220]
(array([10], dtype=int64),)
(array([2, 6], dtype=int64),)


### Question 06

Create a Series with 30 different product names as indexes

and enter random numbers (sales) as values.

* Find best-selling product.
* Compute percentage share of each product.
* Remove products below average sales.

In [86]:
sales_series = pd.Series(np.random.randint(100, 1001, 30),
index=[f"product{i}" for i in range(1, 31)])
min_sale = min(sales_series)
print("product with the least price is:\n", sales_series[sales_series == min_sale].index)
#we concider 20% share for each product
print("percentage share of each product:\n", sales_series * (20 / 100))
mean_sale = sales_series.mean()
print("mean price is:\n", mean_sale)
sales_series = sales_series[sales_series > mean_sale]
print("products with price more than average sales:\n", sales_series)

product with the least price is:
 Index(['product27'], dtype='object')
percentage share of each product:
 product1     141.4
product2     132.6
product3     183.0
product4     172.6
product5      30.0
product6     110.6
product7     145.0
product8     170.8
product9     123.2
product10    128.4
product11     83.4
product12     67.0
product13     33.4
product14     46.8
product15    160.0
product16     51.2
product17    118.6
product18    138.4
product19     98.2
product20    159.6
product21    102.2
product22    163.0
product23    168.4
product24     88.2
product25     45.4
product26    128.2
product27     29.2
product28     92.4
product29    151.2
product30    193.2
dtype: float64
mean price is:
 575.9333333333333
products with price more than average sales:
 product1     707
product2     663
product3     915
product4     863
product7     725
product8     854
product9     616
product10    642
product15    800
product17    593
product18    692
product20    798
product22    815
product2

### Question 07

Create a Series of 100 student with GPA (values between 8 and 20).

Change index of the series with student names.

* Find top 20% Students and print their names.
* Label students above 17 as "Excellent".

In [87]:
gpa = pd.Series(np.round(np.random.uniform(8, 20, 100), 2), index=[f"student{i}" for i in range(1, 101)])
#print(gpa)
threshold = gpa.quantile(0.8)
print(threshold)
#print(gpa[gpa >= threshold])
gpa.index = [
    ("Excellent", idx) if val > 17 else idx 
    for idx, val in gpa.items()
]
print(gpa)

17.992
student1                   9.12
student2                  11.32
student3                   8.10
(Excellent, student4)     19.24
student5                  10.65
                          ...  
student96                 10.57
(Excellent, student97)    17.74
student98                 10.56
(Excellent, student99)    17.16
student100                11.41
Length: 100, dtype: float64


### Question 08

Create a Series of 50 people birthday year (1925 to 2025)

and set indexes with their gender (random Female/Male).

then, separate these 50 pople into 6 different series based on their generation:

* Alpha: Born 2013–2025.
* Z: Born 1997–2012 (Ages 14–29).
* Millennials: Born 1981–1996 (Ages 30–45).
* X: Born 1965–1980 (Ages 46–61).
* Baby Boomers: Born 1946–1964 (Ages 62–80).
* Silent: Born 1925–1945 (Ages 81–101). 

Finally, print number of Female and Male popele in each generation.

In [88]:
birth_year_series = pd.Series(np.random.randint(1925, 2026, 50), index=[np.random.choice(["male", "female"], 50)])

In [95]:
Alpha = {"male": 0, "female": 0}
Z = {"male": 0, "female": 0}
Millennials = {"male": 0, "female": 0}
X = {"male": 0, "female": 0}
BabyBoomers = {"male": 0, "female": 0}
Silent = {"male": 0, "female": 0}

In [99]:
for i, j in birth_year_series.items():
    if j >= 2013 and j <= 2025:
        if i == "male":
            Alpha["male"] += 1
        if i == "female":
            Alpha["female"] += 1
    elif j >= 1997 and j <= 2012:
        if i == "male":
            Z["male"] += 1
        if i == "female":
            Z["female"] += 1
    elif j >= 1981 and j <= 1996:
        if i == "male":
            Millennials["male"] += 1
        if i == "female":
            Millennials["female"] += 1
    elif j >= 1965 and j <= 1980:
        if i == "male":
            X["male"] += 1
        if i == "female":
            X["female"] += 1
    elif j >= 1946 and j <= 1964:
        if i == "male":
            BabyBoomers["male"] += 1
        if i == "female":
            BabyBoomers["female"] += 1
    elif j >= 1925 and j <= 1945:
        if i == "male":
            Silent["male"] += 1
        if i == "female":
            Silent["female"] += 1