### Question 00
import necessary libraries in the box below

In [2]:
import numpy as np

### Question 01
Create a NumPy array from [1,2,3, ..., 12].

In [3]:
array_01 = np.arange(1, 13)

### Question 02
Print the type of array array_01

In [4]:
print(type(array_01))

<class 'numpy.ndarray'>


### Question 03
Reshape array_01 into 3 x 4 matrix.

In [5]:
array_03 = array_01.reshape(3, 4)

### Question 04
Get the length of the array_03.

In [6]:
print(array_03.size)

12


### Question 05
Print the second element of the second row in array_03.

In [7]:
print(array_03[1, 1])

6


### Question 06
Multiply all elements of array_03 by 2.

In [8]:
array_06 = array_03 * 2

### Question 07
Add 5 to all elements of array_06.

In [9]:
print(array_06 + 5)

[[ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


### Question 07
Create an array of 18 zeros.

In [10]:
array_07 = np.zeros(18)

### Question 08
Create an array of 20 fours.

In [11]:
array_08 = np.ones(20) * 4
print(array_08)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


### Question 09
Create numbers from 0 to 20.

In [12]:
array_09 = np.arange(20)

### Question 10
Create 24 random numbers between 0 and 1.
Then, Reshape it into matrix with 6 rows.

In [13]:
array_10 = np.random.random(24)
array_10 = array_10.reshape(6, 4)

### Question 11
Convert array_08 to String type.

In [14]:
array_11 = array_08.astype(str)

### Question 12
Find sum of all rows in array_11

In [15]:
array_12 = array_11.astype(float)
print(array_12.sum(axis = 0))

80.0


### Question 13
Find mean of elements of array_10 'in' each row.

In [17]:
array_14 = array_10

print(array_14.mean(axis = 0))

[0.6166144  0.45497908 0.5233314  0.70009969]


### Question 14
Reverse the array_10.

In [18]:
print(array_10.T)

[[0.94301367 0.94501797 0.86433152 0.37606822 0.0404957  0.53075934]
 [0.1748736  0.67225349 0.15835695 0.63125964 0.25698765 0.83614314]
 [0.1609558  0.5281428  0.43954236 0.63631326 0.76689103 0.60814314]
 [0.48900739 0.7456596  0.96115238 0.69903565 0.82000455 0.48573858]]


### Question 15
Add array [1,2,3,4,5,6] to array_10.

In [35]:
array_15 = np.array([1,2,3,4,5,6])
print(np.append(array_10, array_15))

[0.94301367 0.1748736  0.1609558  0.48900739 0.94501797 0.67225349
 0.5281428  0.7456596  0.86433152 0.15835695 0.43954236 0.96115238
 0.37606822 0.63125964 0.63631326 0.69903565 0.0404957  0.25698765
 0.76689103 0.82000455 0.53075934 0.83614314 0.60814314 0.48573858
 1.         2.         3.         4.         5.         6.        ]


### Question 16
Print odd column of array_10

In [48]:
array_10 = np.array([[1, 3, 2, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
print(array_10[:, 1::2])

[[3 4 6]
 [2 4 6]
 [2 4 6]]


### Question 17
Create 3x3 zeros matrix.

In [46]:
array_17 = np.zeros((3,3))

### Question 18
Sort the array_10.

In [52]:
print(np.sort(array_10))

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


### Question 19
Transpose the array_10 

In [53]:
print(array_10.T)

[[1 1 1]
 [3 2 2]
 [2 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]


### Question 20
Create even numbers from 11 to 56.

In [59]:
array_20 = np.arange(12,56,2)
print(array_20)

[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54]
